[tool.pytest.ini_options]
log_cli = 1
log_cli_level = "INFO"
pythonpath = [".", "test", "src"]
env = [
    "CLIENT_ID=dataportal-webapp",
    "CLIENT_SECRET=piczMMlNFoQuKTjRT4o4FJibPUFuI2bk",
    "USERNAME=test",
    "PASSWORD=supersecretpassword",
    "TOKEN_ACCESS_URL=http://localhost:8083/auth/realms/dataportal/protocol/openid-connect/token",
    "TERMINOLOGY_SERVER_ADDRESS=https://ontoserver.mii-termserv.de/fhir",
    "SQ2CQL_VERSION=1.2.0"
]
