fhir-packages:
  manager:
    type: "github"
    params:
      org: "medizininformatik-initiative"
      repo: "fhir-package-store"
      ref: "main"
      path: "package-tarballs"
http:
  timeout: "PT30S"
  retries: null
  backoff_factor: 1
